using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security.AccessControl;
using System.Security.Principal;
using System.Windows.Forms;
using Microsoft.Win32;
using Microsoft.Win32.SafeHandles;
using WireSockUI.Config;
using WireSockUI.Extensions;
using WireSockUI.Forms;
using WireSockUI.Properties;

namespace WireSockUI
{
    internal static class Program
    {
        private const long MaxMigratedProfileSizeBytes = 1024 * 1024;
        private const uint GenericRead = 0x80000000;
        private const uint FileShareRead = 0x00000001;
        private const uint OpenExisting = 3;
        private const uint FileFlagOpenReparsePoint = 0x00200000;
        private const uint FileFlagSequentialScan = 0x08000000;

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        private static extern bool SetDllDirectory(string lpPathName);

        [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
        private static extern SafeFileHandle CreateFile(
            string lpFileName,
            uint dwDesiredAccess,
            uint dwShareMode,
            IntPtr lpSecurityAttributes,
            uint dwCreationDisposition,
            uint dwFlagsAndAttributes,
            IntPtr hTemplateFile);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool GetFileInformationByHandle(
            SafeFileHandle hFile,
            out ByHandleFileInformation lpFileInformation);

        [StructLayout(LayoutKind.Sequential, Pack = 4)]
        private struct ByHandleFileInformation
        {
            public FileAttributes FileAttributes;
            public FileTime CreationTime;
            public FileTime LastAccessTime;
            public FileTime LastWriteTime;
            public uint VolumeSerialNumber;
            public uint FileSizeHigh;
            public uint FileSizeLow;
            public uint NumberOfLinks;
            public uint FileIndexHigh;
            public uint FileIndexLow;
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct FileTime
        {
            public uint LowDateTime;
            public uint HighDateTime;
        }

        [STAThread]
        private static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            try
            {
                Global.EnsureApplicationFolders();
                MigrateLegacyProfiles();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Unable to initialize WireSock UI profile folders.{Environment.NewLine}{Environment.NewLine}{ex.Message}",
                    Resources.AppNoWireSockTitle, MessageBoxButtons.OK, MessageBoxIcon.Error);
                Environment.Exit(1);
            }

            if (!IsWireSockArchitectureSupported())
            {
                MessageBox.Show(Resources.AppUnsupportedArchMessage, Resources.AppNoWireSockTitle,
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
                Environment.Exit(1);
            }

            if (!IsWireSockInstalled())
            {
                MessageBox.Show(Resources.AppNoWireSockMessage, Resources.AppNoWireSockTitle, MessageBoxButtons.OK,
                    MessageBoxIcon.Information);
                OpenBrowser(Resources.AppWireSockURL);

                Environment.Exit(1);
            }

#if WIRESOCKUI_ENABLE_UWP
            CheckVersion();
#endif

            Application.Run(new FrmMain());
        }

        private static void OpenBrowser(string url)
        {
            try
            {
                Process.Start(url);
            }
            catch (Exception ex)
            {
                Trace.TraceWarning($"Failed to open browser for '{url}': {ex.Message}");
            }
        }

        /// <summary>
        ///     Determine if this WireSockUI was generated by an automated build from a GitHub repository
        /// </summary>
        /// <returns>Assembly repository if set during build</returns>
        private static string GetRepository()
        {
            var assembly = Assembly.GetExecutingAssembly();

            foreach (var metadata in assembly.GetCustomAttributes<AssemblyMetadataAttribute>())
                if (string.Equals(metadata.Key, "Repository"))
                    return metadata.Value;

            return null;
        }

#if WIRESOCKUI_ENABLE_UWP
        /// <summary>
        ///     Compare the local product version against the latest GitHub repository release tag
        /// </summary>
        /// <remarks>If auto update is enabled, repository is known and there is a new version, open up a browser window.</remarks>
        private static void CheckVersion()
        {
            if (!Settings.Default.AutoUpdate) return;
        
            try
            {
                var repository = GetRepository();
        
                if (!string.IsNullOrWhiteSpace(repository))
                {
                    var currentVersion = new Version(Application.ProductVersion);
                    var latestVersion = GitHubExtensions.GetLatestRelease(repository);
        
                    if (currentVersion != null && latestVersion != null && latestVersion > currentVersion)
                    {
                        var dialogResult = MessageBox.Show(Resources.AppUpdateMessage, Resources.AppUpdateTitle, MessageBoxButtons.OKCancel,
                            MessageBoxIcon.Information);
        
                        if (dialogResult == DialogResult.OK)
                        {
                            OpenBrowser($"https://github.com/{repository}/releases");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                // user possibly doesn't have internet
                
            }
        }
#endif

        /// <summary>
        ///     Determine if the WireSock library components are installed.
        /// </summary>
        /// <returns><c>true</c> if installed, otherwise <c>false</c></returns>
        private static bool IsWireSockInstalled()
        {
            string libraryDirectory;
            if (!TryFindWireSockLibraryDirectory(out libraryDirectory))
                return false;

            return ConfigureWireSockLibraryDirectory(libraryDirectory);
        }

        private static bool TryFindWireSockLibraryDirectory(out string libraryDirectory)
        {
            libraryDirectory = null;

            var localDirectory = AppDomain.CurrentDomain.BaseDirectory;
            if (TryValidateWireSockLibraryDirectory(localDirectory, out libraryDirectory))
                return true;

            foreach (var installLocation in GetInstallLocations())
            {
                foreach (var candidate in GetLibraryDirectories(installLocation))
                {
                    if (TryValidateWireSockLibraryDirectory(candidate, out libraryDirectory))
                        return true;
                }
            }

            return false;
        }

        private static bool TryValidateWireSockLibraryDirectory(string directory, out string libraryDirectory)
        {
            libraryDirectory = null;

            var fullDirectory = NormalizePathDirectory(directory);
            if (fullDirectory == null ||
                !TryGetExistingAttributes(fullDirectory, out var directoryAttributes) ||
                (directoryAttributes & FileAttributes.Directory) == 0)
                return false;

            if ((directoryAttributes & FileAttributes.ReparsePoint) != 0)
            {
                Trace.TraceWarning(
                    $"Skipping WireSock library directory '{fullDirectory}' because it is a reparse point.");
                return false;
            }

            if (IsPotentiallyUserWritableDirectory(fullDirectory))
            {
                Trace.TraceWarning(
                    $"Skipping WireSock library directory '{fullDirectory}' because it is writable by non-administrative users.");
                return false;
            }

            var libraryPath = Path.Combine(fullDirectory, "wgbooster.dll");
            if (!TryGetExistingAttributes(libraryPath, out var libraryAttributes))
                return false;

            if ((libraryAttributes & FileAttributes.Directory) != 0)
            {
                Trace.TraceWarning(
                    $"Skipping WireSock library '{libraryPath}' because it is a directory.");
                return false;
            }

            if ((libraryAttributes & FileAttributes.ReparsePoint) != 0)
            {
                Trace.TraceWarning(
                    $"Skipping WireSock library '{libraryPath}' because it is a reparse point.");
                return false;
            }

            if (IsPotentiallyUserWritableFile(libraryPath))
            {
                Trace.TraceWarning(
                    $"Skipping WireSock library '{libraryPath}' because it is writable by non-administrative users.");
                return false;
            }

            libraryDirectory = fullDirectory;
            return true;
        }

        private static string[] GetLibraryDirectories(string installLocation)
        {
            if (string.IsNullOrWhiteSpace(installLocation))
                return new string[0];

            var directories = new List<string>();
            AddLibraryDirectory(directories, installLocation, "sdk");
            AddLibraryDirectory(directories, installLocation, "bin");
            directories.Add(installLocation);

            return directories.ToArray();
        }

        private static void AddLibraryDirectory(List<string> directories, string path1, string path2)
        {
            try
            {
                directories.Add(Path.Combine(path1, path2));
            }
            catch (Exception ex)
            {
                Trace.TraceWarning(
                    $"Skipping invalid WireSock library candidate '{path1}{Path.DirectorySeparatorChar}{path2}': {ex.Message}");
            }
        }

        private static string[] GetInstallLocations()
        {
            var locations = new List<string>();
            var registryPaths = new[]
            {
                "SOFTWARE\\WireSock Foundation\\WireSock Secure Connect",
                "SOFTWARE\\WireSock Foundation\\WireSock Secure Connect Pro",
                "SOFTWARE\\NTKernelResources\\WinpkFilterForVPNClient"
            };

            var registryViews = new[] { RegistryView.Registry64, RegistryView.Registry32 };
            foreach (var view in registryViews)
            {
                RegistryKey baseKey = null;
                try
                {
                    baseKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, view);
                }
                catch
                {
                    continue;
                }

                using (baseKey)
                {
                    foreach (var registryPath in registryPaths)
                    {
                        using (var key = baseKey.OpenSubKey(registryPath))
                        {
                            var value = key?.GetValue("InstallLocation") as string;
                            if (string.IsNullOrWhiteSpace(value))
                                continue;

                            if (!locations.Exists(path =>
                                    string.Equals(path, value, StringComparison.OrdinalIgnoreCase)))
                                locations.Add(value);
                        }
                    }
                }
            }

            return locations.ToArray();
        }

        private static bool ConfigureWireSockLibraryDirectory(string directory)
        {
            if (string.IsNullOrWhiteSpace(directory))
                return false;

            var fullDirectory = NormalizePathDirectory(directory);
            if (fullDirectory == null)
                return false;

            var appDirectory = NormalizePathDirectory(AppDomain.CurrentDomain.BaseDirectory);
            var isAppLocalDirectory = string.Equals(fullDirectory, appDirectory, StringComparison.OrdinalIgnoreCase);

            try
            {
                if (SetDllDirectory(fullDirectory))
                    return true;

                Trace.TraceWarning(
                    $"Failed to set WireSock library directory '{fullDirectory}': {new Win32Exception(Marshal.GetLastWin32Error()).Message}");
            }
            catch (Exception ex)
            {
                Trace.TraceWarning($"Failed to set WireSock library directory '{fullDirectory}': {ex.Message}");
            }

            return isAppLocalDirectory;
        }

        private static void MigrateLegacyProfiles()
        {
            if (!Directory.Exists(Global.LegacyConfigsFolder))
                return;

            if (!TryIsReparsePoint(Global.LegacyConfigsFolder, out var legacyConfigsIsReparsePoint) ||
                legacyConfigsIsReparsePoint)
            {
                Trace.TraceWarning(
                    $"Skipping legacy profile migration because '{Global.LegacyConfigsFolder}' is a reparse point or cannot be inspected.");
                return;
            }

            string[] legacyProfilePaths;
            try
            {
                legacyProfilePaths = Directory.GetFiles(Global.LegacyConfigsFolder, "*.conf");
            }
            catch (Exception ex)
            {
                Trace.TraceWarning($"Unable to enumerate legacy WireSock UI profiles: {ex.Message}");
                return;
            }

            foreach (var legacyProfilePath in legacyProfilePaths)
            {
                if (!TryIsReparsePoint(legacyProfilePath, out var legacyProfileIsReparsePoint) ||
                    legacyProfileIsReparsePoint)
                {
                    Trace.TraceWarning(
                        $"Skipping legacy profile '{Path.GetFileName(legacyProfilePath)}' because it is a reparse point or cannot be inspected.");
                    continue;
                }

                var profileName = Path.GetFileNameWithoutExtension(legacyProfilePath);
                if (!Profile.IsValidProfileName(profileName))
                {
                    Trace.TraceWarning($"Skipping legacy profile with unsafe name '{Path.GetFileName(legacyProfilePath)}'.");
                    continue;
                }

                var destinationPath = Profile.GetProfilePath(profileName);
                if (Profile.ProfilePathExists(destinationPath))
                {
                    if (!Profile.IsRegularProfileFile(destinationPath, out var diagnostic))
                    {
                        Trace.TraceWarning(
                            $"Skipping legacy profile '{profileName}' because the secured profile path is unsafe: {diagnostic}");
                        continue;
                    }

                    if (FilesHaveSameContent(legacyProfilePath, destinationPath))
                        TryDeleteLegacyProfile(legacyProfilePath, profileName);
                    else
                        Trace.TraceWarning(
                            $"Skipping legacy profile '{profileName}' because a secured profile with different content already exists.");

                    continue;
                }

                if (TryCopyLegacyProfileToSecureProfile(legacyProfilePath, destinationPath, profileName))
                    TryDeleteLegacyProfile(legacyProfilePath, profileName);
            }
        }

        private static bool TryCopyLegacyProfileToSecureProfile(string legacyProfilePath, string destinationPath,
            string profileName)
        {
            var tmpProfile = Path.Combine(Global.ConfigsFolder, $"{Guid.NewGuid():N}.tmp");

            try
            {
                CopyLegacyProfileToTemporaryFile(legacyProfilePath, tmpProfile);
                File.Move(tmpProfile, destinationPath);
                tmpProfile = null;
                return true;
            }
            catch (Exception ex)
            {
                Trace.TraceWarning($"Failed to migrate legacy profile '{profileName}': {ex.Message}");
                return false;
            }
            finally
            {
                if (tmpProfile != null)
                    TryDeleteTemporaryMigratedProfile(tmpProfile, profileName);
            }
        }

        private static void CopyLegacyProfileToTemporaryFile(string sourcePath, string destinationPath)
        {
            using (var source = OpenLegacyProfileForRead(sourcePath))
            {
                if (source.Length > MaxMigratedProfileSizeBytes)
                    throw new InvalidOperationException("The legacy profile file is too large to be migrated.");

                using (var destination = new FileStream(destinationPath, FileMode.CreateNew, FileAccess.Write,
                           FileShare.None))
                {
                    var buffer = new byte[81920];
                    long bytesCopied = 0;
                    int bytesRead;

                    while ((bytesRead = source.Read(buffer, 0, buffer.Length)) > 0)
                    {
                        bytesCopied += bytesRead;
                        if (bytesCopied > MaxMigratedProfileSizeBytes)
                            throw new InvalidOperationException("The legacy profile file is too large to be migrated.");

                        destination.Write(buffer, 0, bytesRead);
                    }
                }
            }
        }

        private static FileStream OpenLegacyProfileForRead(string sourcePath)
        {
            var handle = CreateFile(
                sourcePath,
                GenericRead,
                FileShareRead,
                IntPtr.Zero,
                OpenExisting,
                FileFlagOpenReparsePoint | FileFlagSequentialScan,
                IntPtr.Zero);

            if (handle.IsInvalid)
            {
                handle.Dispose();
                throw new IOException(
                    $"Unable to open legacy profile '{Path.GetFileName(sourcePath)}'.",
                    new Win32Exception(Marshal.GetLastWin32Error()));
            }

            try
            {
                if (!GetFileInformationByHandle(handle, out var fileInformation))
                    throw new IOException(
                        $"Unable to inspect legacy profile '{Path.GetFileName(sourcePath)}'.",
                        new Win32Exception(Marshal.GetLastWin32Error()));

                if ((fileInformation.FileAttributes & FileAttributes.ReparsePoint) != 0)
                    throw new IOException(
                        $"Legacy profile '{Path.GetFileName(sourcePath)}' is a reparse point.");

                if ((fileInformation.FileAttributes & FileAttributes.Directory) != 0)
                    throw new IOException(
                        $"Legacy profile '{Path.GetFileName(sourcePath)}' is a directory.");

                return new FileStream(handle, FileAccess.Read, 81920, false);
            }
            catch
            {
                handle.Dispose();
                throw;
            }
        }

        private static bool TryIsReparsePoint(string path, out bool isReparsePoint)
        {
            isReparsePoint = false;

            if (!TryGetExistingAttributes(path, out var attributes, true))
                return false;

            isReparsePoint = (attributes & FileAttributes.ReparsePoint) != 0;
            return true;
        }

        private static bool TryGetExistingAttributes(string path, out FileAttributes attributes,
            bool warnOnFailure = false)
        {
            attributes = 0;

            try
            {
                attributes = File.GetAttributes(path);
                return true;
            }
            catch (FileNotFoundException)
            {
                return false;
            }
            catch (DirectoryNotFoundException)
            {
                return false;
            }
            catch (Exception ex)
            {
                if (warnOnFailure)
                    Trace.TraceWarning($"Unable to inspect file system attributes for '{path}': {ex.Message}");

                return false;
            }
        }

        private static bool FilesHaveSameContent(string firstPath, string secondPath)
        {
            try
            {
                using (var first = OpenLegacyProfileForRead(firstPath))
                using (var second = File.OpenRead(secondPath))
                {
                    if (first.Length != second.Length)
                        return false;

                    var firstBuffer = new byte[81920];
                    var secondBuffer = new byte[81920];

                    while (true)
                    {
                        var firstBytesRead = ReadBlock(first, firstBuffer);
                        var secondBytesRead = ReadBlock(second, secondBuffer);
                        if (firstBytesRead != secondBytesRead)
                            return false;

                        if (firstBytesRead == 0)
                            return true;

                        for (var i = 0; i < firstBytesRead; i++)
                        {
                            if (firstBuffer[i] != secondBuffer[i])
                                return false;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Trace.TraceWarning($"Failed to compare migrated profile files: {ex.Message}");
                return false;
            }
        }

        private static int ReadBlock(Stream stream, byte[] buffer)
        {
            var totalRead = 0;
            while (totalRead < buffer.Length)
            {
                var bytesRead = stream.Read(buffer, totalRead, buffer.Length - totalRead);
                if (bytesRead == 0)
                    break;

                totalRead += bytesRead;
            }

            return totalRead;
        }

        private static void TryDeleteTemporaryMigratedProfile(string tmpProfile, string profileName)
        {
            try
            {
                if (File.Exists(tmpProfile))
                    File.Delete(tmpProfile);
            }
            catch (Exception ex)
            {
                Trace.TraceWarning(
                    $"Failed to delete temporary migrated profile for '{profileName}': {ex.Message}");
            }
        }

        private static void TryDeleteLegacyProfile(string legacyProfilePath, string profileName)
        {
            try
            {
                File.Delete(legacyProfilePath);
            }
            catch (Exception ex)
            {
                Trace.TraceWarning($"Migrated legacy profile '{profileName}', but could not delete the old copy: {ex.Message}");
            }
        }

        private static bool IsPotentiallyUserWritableDirectory(string directory)
        {
            var normalizedDirectory = NormalizePathDirectory(directory);
            if (normalizedDirectory == null)
                return true;

            try
            {
                var security = Directory.GetAccessControl(normalizedDirectory);
                var rules = security.GetAccessRules(true, true, typeof(SecurityIdentifier));
                return ContainsPotentiallyUserWritableRule(rules);
            }
            catch (Exception ex)
            {
                Trace.TraceWarning($"Unable to inspect ACL for '{normalizedDirectory}': {ex.Message}");
                return true;
            }
        }

        private static bool IsPotentiallyUserWritableFile(string file)
        {
            var normalizedFile = NormalizePathFile(file);
            if (normalizedFile == null)
                return true;

            try
            {
                var security = File.GetAccessControl(normalizedFile);
                var rules = security.GetAccessRules(true, true, typeof(SecurityIdentifier));
                return ContainsPotentiallyUserWritableRule(rules);
            }
            catch (Exception ex)
            {
                Trace.TraceWarning($"Unable to inspect ACL for '{normalizedFile}': {ex.Message}");
                return true;
            }
        }

        private static bool ContainsPotentiallyUserWritableRule(AuthorizationRuleCollection rules)
        {
            const FileSystemRights writeRights =
                FileSystemRights.FullControl |
                FileSystemRights.Modify |
                FileSystemRights.Write |
                FileSystemRights.WriteData |
                FileSystemRights.CreateFiles |
                FileSystemRights.AppendData |
                FileSystemRights.CreateDirectories |
                FileSystemRights.WriteAttributes |
                FileSystemRights.WriteExtendedAttributes |
                FileSystemRights.ChangePermissions |
                FileSystemRights.TakeOwnership |
                FileSystemRights.Delete |
                FileSystemRights.DeleteSubdirectoriesAndFiles;

            foreach (FileSystemAccessRule rule in rules)
            {
                if (rule.AccessControlType != AccessControlType.Allow ||
                    !(rule.IdentityReference is SecurityIdentifier sid) ||
                    (rule.FileSystemRights & writeRights) == 0)
                    continue;

                if (sid.IsWellKnown(WellKnownSidType.CreatorOwnerSid))
                {
                    if ((rule.PropagationFlags & PropagationFlags.InheritOnly) != 0)
                        continue;

                    return true;
                }

                if (!IsAdministrativeOrServiceSid(sid))
                    return true;
            }

            return false;
        }

        private static bool IsAdministrativeOrServiceSid(SecurityIdentifier sid)
        {
            return sid.IsWellKnown(WellKnownSidType.LocalSystemSid) ||
                   sid.IsWellKnown(WellKnownSidType.BuiltinAdministratorsSid) ||
                   sid.IsWellKnown(WellKnownSidType.LocalServiceSid) ||
                   sid.IsWellKnown(WellKnownSidType.NetworkServiceSid) ||
                   sid.Value.StartsWith("S-1-5-80-", StringComparison.OrdinalIgnoreCase) ||
                   sid.Value.StartsWith("S-1-5-83-", StringComparison.OrdinalIgnoreCase);
        }

        private static string NormalizePathDirectory(string directory)
        {
            if (string.IsNullOrWhiteSpace(directory))
                return null;

            try
            {
                return NormalizePathRoot(Path.GetFullPath(directory.Trim().Trim('"')));
            }
            catch (Exception ex)
            {
                Trace.TraceWarning($"Skipping invalid PATH directory '{directory}': {ex.Message}");
                return null;
            }
        }

        private static string NormalizePathFile(string file)
        {
            if (string.IsNullOrWhiteSpace(file))
                return null;

            try
            {
                return NormalizePathRoot(Path.GetFullPath(file.Trim().Trim('"')));
            }
            catch (Exception ex)
            {
                Trace.TraceWarning($"Skipping invalid file path '{file}': {ex.Message}");
                return null;
            }
        }

        private static string NormalizePathRoot(string fullPath)
        {
            var root = Path.GetPathRoot(fullPath);
            if (!string.IsNullOrEmpty(root) &&
                string.Equals(fullPath, root, StringComparison.OrdinalIgnoreCase))
                return fullPath;

            return fullPath.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        }

        /// <summary>
        ///     Determine if running under a supported architecture.
        /// </summary>
        /// <remarks>
        ///     WireSock VPN Client's wgbooster.dll currently forces us to match the operating system's architecture. Under
        ///     normal circumstances this check always succeeds, but under a debugger AnyCPU builds may run as x86 or x64
        ///     processes, disregarding the host OS bitness.
        /// </remarks>
        /// <returns><c>true</c> if supported, otherwise <c>false</c></returns>
        private static bool IsWireSockArchitectureSupported()
        {
            return Environment.Is64BitOperatingSystem == Environment.Is64BitProcess;
        }
    }
}
