using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Windows.Forms;
using Microsoft.Win32;
using WireSockUI.Extensions;
using WireSockUI.Forms;
using WireSockUI.Properties;

namespace WireSockUI
{
    internal static class Program
    {
        [STAThread]
        private static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            if (!Directory.Exists(Global.MainFolder)) Directory.CreateDirectory(Global.MainFolder);
            if (!Directory.Exists(Global.ConfigsFolder)) Directory.CreateDirectory(Global.ConfigsFolder);

            if (!IsWireSockArchitectureSupported())
            {
                MessageBox.Show(Resources.AppUnsupportedArchMessage, Resources.AppNoWireSockTitle,
                    MessageBoxButtons.OK, MessageBoxIcon.Error);
                Environment.Exit(1);
            }

            if (!IsWireSockInstalled())
            {
                MessageBox.Show(Resources.AppNoWireSockMessage, Resources.AppNoWireSockTitle, MessageBoxButtons.OK,
                    MessageBoxIcon.Information);
                OpenBrowser(Resources.AppWireSockURL);

                Environment.Exit(1);
            }

#if WIRESOCKUI_ENABLE_UWP
            CheckVersion();
#endif

            Application.Run(new FrmMain());
        }

        private static void OpenBrowser(string url)
        {
            try
            {
                Process.Start(url);
            }
            catch
            {
            }
        }

        /// <summary>
        ///     Determine if this WireSockUI was generated by an automated build from a GitHub repository
        /// </summary>
        /// <returns>Assembly repository if set during build</returns>
        private static string GetRepository()
        {
            var assembly = Assembly.GetExecutingAssembly();

            foreach (var metadata in assembly.GetCustomAttributes<AssemblyMetadataAttribute>())
                if (string.Equals(metadata.Key, "Repository"))
                    return metadata.Value;

            return null;
        }

#if WIRESOCKUI_ENABLE_UWP
        /// <summary>
        ///     Compare the local product version against the latest GitHub repository release tag
        /// </summary>
        /// <remarks>If auto update is enabled, repository is known and there is a new version, open up a browser window.</remarks>
        private static void CheckVersion()
        {
            if (!Settings.Default.AutoUpdate) return;
        
            try
            {
                var repository = GetRepository();
        
                if (!string.IsNullOrWhiteSpace(repository))
                {
                    var currentVersion = new Version(Application.ProductVersion);
                    var latestVersion = GitHubExtensions.GetLatestRelease(repository);
        
                    if (currentVersion != null && latestVersion != null && latestVersion > currentVersion)
                    {
                        var dialogResult = MessageBox.Show(Resources.AppUpdateMessage, Resources.AppUpdateTitle, MessageBoxButtons.OKCancel,
                            MessageBoxIcon.Information);
        
                        if (dialogResult == DialogResult.OK)
                        {
                            OpenBrowser($"https://github.com/{repository}/releases");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                // user possibly doesn't have internet
                
            }
        }
#endif

        /// <summary>
        ///     Determine if the WireSock library components are installed.
        /// </summary>
        /// <returns><c>true</c> if installed, otherwise <c>false</c></returns>
        private static bool IsWireSockInstalled()
        {
            string libraryDirectory;
            if (!TryFindWireSockLibraryDirectory(out libraryDirectory))
                return false;

            AddDirectoryToProcessPath(libraryDirectory);
            return true;
        }

        private static bool TryFindWireSockLibraryDirectory(out string libraryDirectory)
        {
            libraryDirectory = null;

            var localDirectory = AppDomain.CurrentDomain.BaseDirectory;
            if (ContainsWireSockLibrary(localDirectory))
            {
                libraryDirectory = localDirectory;
                return true;
            }

            foreach (var pathDirectory in GetPathDirectories())
            {
                if (!ContainsWireSockLibrary(pathDirectory))
                    continue;

                libraryDirectory = pathDirectory;
                return true;
            }

            foreach (var installLocation in GetInstallLocations())
            {
                foreach (var candidate in GetLibraryDirectories(installLocation))
                {
                    if (!ContainsWireSockLibrary(candidate))
                        continue;

                    libraryDirectory = candidate;
                    return true;
                }
            }

            return false;
        }

        private static bool ContainsWireSockLibrary(string directory)
        {
            return !string.IsNullOrWhiteSpace(directory) &&
                   File.Exists(Path.Combine(directory, "wgbooster.dll"));
        }

        private static string[] GetLibraryDirectories(string installLocation)
        {
            if (string.IsNullOrWhiteSpace(installLocation))
                return new string[0];

            return new[]
            {
                Path.Combine(installLocation, "sdk"),
                Path.Combine(installLocation, "bin"),
                installLocation
            };
        }

        private static string[] GetInstallLocations()
        {
            var locations = new List<string>();
            var registryPaths = new[]
            {
                "SOFTWARE\\WireSock Foundation\\WireSock Secure Connect",
                "SOFTWARE\\WireSock Foundation\\WireSock Secure Connect Pro",
                "SOFTWARE\\NTKernelResources\\WinpkFilterForVPNClient"
            };

            var registryViews = new[] { RegistryView.Registry64, RegistryView.Registry32 };
            foreach (var view in registryViews)
            {
                RegistryKey baseKey = null;
                try
                {
                    baseKey = RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, view);
                }
                catch
                {
                    continue;
                }

                using (baseKey)
                {
                    foreach (var registryPath in registryPaths)
                    {
                        using (var key = baseKey.OpenSubKey(registryPath))
                        {
                            var value = key?.GetValue("InstallLocation") as string;
                            if (string.IsNullOrWhiteSpace(value))
                                continue;

                            if (!locations.Exists(path =>
                                    string.Equals(path, value, StringComparison.OrdinalIgnoreCase)))
                                locations.Add(value);
                        }
                    }
                }
            }

            return locations.ToArray();
        }

        private static IEnumerable<string> GetPathDirectories()
        {
            var environmentPath = Environment.GetEnvironmentVariable("PATH") ?? string.Empty;

            foreach (var item in environmentPath.Split(Path.PathSeparator))
            {
                var directory = item.Trim().Trim('"');
                if (!string.IsNullOrWhiteSpace(directory))
                    yield return directory;
            }
        }

        private static void AddDirectoryToProcessPath(string directory)
        {
            if (string.IsNullOrWhiteSpace(directory))
                return;

            var fullDirectory = Path.GetFullPath(directory).TrimEnd(Path.DirectorySeparatorChar);
            var environmentPath = Environment.GetEnvironmentVariable("PATH") ?? string.Empty;

            foreach (var item in environmentPath.Split(Path.PathSeparator))
            {
                if (string.Equals(item.Trim().TrimEnd(Path.DirectorySeparatorChar), fullDirectory,
                        StringComparison.OrdinalIgnoreCase))
                    return;
            }

            Environment.SetEnvironmentVariable("PATH", $"{fullDirectory}{Path.PathSeparator}{environmentPath}");
        }

        /// <summary>
        ///     Determine if running under a supported architecture.
        /// </summary>
        /// <remarks>
        ///     WireSock VPN Client's wgbooster.dll currently forces us to match the operating system's architecture. Under
        ///     normal circumstances this check always succeeds, but under a debugger AnyCPU builds may run as x86 or x64
        ///     processes, disregarding the host OS bitness.
        /// </remarks>
        /// <returns><c>true</c> if supported, otherwise <c>false</c></returns>
        private static bool IsWireSockArchitectureSupported()
        {
            return Environment.Is64BitOperatingSystem == Environment.Is64BitProcess;
        }
    }
}
